version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo install phase
  pre_build:
    commands:
      - echo pre_build phase
      - echo `java -version`
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain pk-demo --domain-owner 515656444959 --region ap-southeast-2 --query authorizationToken --output text`
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build publish
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/pk-demo-codebuild-0.0.1-SNAPSHOT.jar